{
 "title": "DevOps API Dashboard",
 "tags": [
  "devops-api",
  "flask",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Methods Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method) (rate(flask_http_request_total[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}